spring:
  application:
    name: auth-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://${CLOUD_CONFIG_USERNAME}:${CLOUD_CONFIG_PASSWORD}@${CLOUD_CONFIG_IP}:${CLOUD_CONFIG_PORT}